server.port=80
spring.application.name=ProjectFinal

# MariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/project
#spring.datasource.url=jdbc:mysql://localhost:3309/project
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234

# adminController image upload url
# **/uploads/images
upload.path=C:/Users/TJ/AKDM/uploads/images
#upload.path=C:/Users/goun8/AKDM/uploads/images

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=1000
logging.level.org.hibernate.type.descriptor.sql=trace

spring.task.scheduling.pool.size=1

logging.level.org.springframework=INFO
logging.level.com.example.jobcrawler=DEBUG

spring.servlet.multipart.maxFileSize=20MB
spring.servlet.multipart.maxRequestSize=100MB

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200
spring.jackson.time-zone=Asia/Seoul


#spring.elasticsearch.username=elastic     # need
#spring.elasticsearch.password=yourpassword # need

spring.data.elasticsearch.create-index=false
spring.data.elasticsearch.schema-management.enabled=false

# application.properties
openai.api.key=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